/**
 * COPILOT TOOLS SDK v3.0.1
 * Tested with: https://app.copilot.money v26.1.8-beta.1214 (Build: 630)
 * Comprehensive Transaction Management SDK for Copilot.money
 * Updated: 2026-01-08
 */

(function() {
  window.CopilotTools = window.CopilotTools || {};
  CopilotTools.VERSION = "3.0.1";
  CopilotTools.COLORS = {RED1:"RED1",RED2:"RED2",ORANGE1:"ORANGE1",ORANGE2:"ORANGE2",YELLOW1:"YELLOW1",YELLOW2:"YELLOW2",GREEN1:"GREEN1",GREEN2:"GREEN2",TEAL1:"TEAL1",TEAL2:"TEAL2",BLUE1:"BLUE1",BLUE2:"BLUE2",PURPLE1:"PURPLE1",PURPLE2:"PURPLE2",PINK1:"PINK1",PINK2:"PINK2",GRAY1:"GRAY1",GRAY2:"GRAY2"};
  CopilotTools.TRANSACTION_TYPES = {REGULAR:"REGULAR",INCOME:"INCOME",INTERNAL_TRANSFER:"INTERNAL_TRANSFER"};
  CopilotTools.config = {rateLimit:300,logPrefix:"[CopilotTools]",verbose:true};
  CopilotTools._categorizationRules = [];

  // Logging
  CopilotTools.log = function(msg) { if(CopilotTools.config.verbose) console.log(CopilotTools.config.logPrefix + " " + msg); };
  CopilotTools.warn = function(msg) { console.warn(CopilotTools.config.logPrefix + " " + msg); };
  CopilotTools.error = function(msg) { console.error(CopilotTools.config.logPrefix + " " + msg); };
  CopilotTools._delay = function(ms) { return new Promise(function(r){setTimeout(r,ms);}); };

  // GRAPHQL MUTATIONS
  CopilotTools.mutations = {};

  CopilotTools.mutations.CREATE_TRANSACTION = {kind:"Document",definitions:[{kind:"OperationDefinition",operation:"mutation",name:{kind:"Name",value:"CreateTransaction"},variableDefinitions:[{kind:"VariableDefinition",variable:{kind:"Variable",name:{kind:"Name",value:"accountId"}},type:{kind:"NonNullType",type:{kind:"NamedType",name:{kind:"Name",value:"ID"}}}},{kind:"VariableDefinition",variable:{kind:"Variable",name:{kind:"Name",value:"itemId"}},type:{kind:"NonNullType",type:{kind:"NamedType",name:{kind:"Name",value:"ID"}}}},{kind:"VariableDefinition",variable:{kind:"Variable",name:{kind:"Name",value:"input"}},type:{kind:"NonNullType",type:{kind:"NamedType",name:{kind:"Name",value:"CreateTransactionInput"}}}}],selectionSet:{kind:"SelectionSet",selections:[{kind:"Field",name:{kind:"Name",value:"createTransaction"},arguments:[{kind:"Argument",name:{kind:"Name",value:"accountId"},value:{kind:"Variable",name:{kind:"Name",value:"accountId"}}},{kind:"Argument",name:{kind:"Name",value:"itemId"},value:{kind:"Variable",name:{kind:"Name",value:"itemId"}}},{kind:"Argument",name:{kind:"Name",value:"input"},value:{kind:"Variable",name:{kind:"Name",value:"input"}}}],selectionSet:{kind:"SelectionSet",selections:[{kind:"Field",name:{kind:"Name",value:"id"}},{kind:"Field",name:{kind:"Name",value:"name"}},{kind:"Field",name:{kind:"Name",value:"amount"}},{kind:"Field",name:{kind:"Name",value:"date"}},{kind:"Field",name:{kind:"Name",value:"type"}},{kind:"Field",name:{kind:"Name",value:"accountId"}},{kind:"Field",name:{kind:"Name",value:"categoryId"}},{kind:"Field",name:{kind:"Name",value:"userNotes"}}]}}]}}]};
  CopilotTools.mutations.DELETE_TRANSACTION = {kind:"Document",definitions:[{kind:"OperationDefinition",operation:"mutation",name:{kind:"Name",value:"DeleteTransaction"},variableDefinitions:[{kind:"VariableDefinition",variable:{kind:"Variable",name:{kind:"Name",value:"accountId"}},type:{kind:"NonNullType",type:{kind:"NamedType",name:{kind:"Name",value:"ID"}}}},{kind:"VariableDefinition",variable:{kind:"Variable",name:{kind:"Name",value:"itemId"}},type:{kind:"NonNullType",type:{kind:"NamedType",name:{kind:"Name",value:"ID"}}}},{kind:"VariableDefinition",variable:{kind:"Variable",name:{kind:"Name",value:"id"}},type:{kind:"NonNullType",type:{kind:"NamedType",name:{kind:"Name",value:"ID"}}}}],selectionSet:{kind:"SelectionSet",selections:[{kind:"Field",name:{kind:"Name",value:"deleteTransaction"},arguments:[{kind:"Argument",name:{kind:"Name",value:"accountId"},value:{kind:"Variable",name:{kind:"Name",value:"accountId"}}},{kind:"Argument",name:{kind:"Name",value:"itemId"},value:{kind:"Variable",name:{kind:"Name",value:"itemId"}}},{kind:"Argument",name:{kind:"Name",value:"id"},value:{kind:"Variable",name:{kind:"Name",value:"id"}}}]}]}}]};

  CopilotTools.mutations.CREATE_TAG = {kind:"Document",definitions:[{kind:"OperationDefinition",operation:"mutation",name:{kind:"Name",value:"CreateTag"},variableDefinitions:[{kind:"VariableDefinition",variable:{kind:"Variable",name:{kind:"Name",value:"input"}},type:{kind:"NonNullType",type:{kind:"NamedType",name:{kind:"Name",value:"CreateTagInput"}}}}],selectionSet:{kind:"SelectionSet",selections:[{kind:"Field",name:{kind:"Name",value:"createTag"},arguments:[{kind:"Argument",name:{kind:"Name",value:"input"},value:{kind:"Variable",name:{kind:"Name",value:"input"}}}],selectionSet:{kind:"SelectionSet",selections:[{kind:"Field",name:{kind:"Name",value:"id"}},{kind:"Field",name:{kind:"Name",value:"name"}},{kind:"Field",name:{kind:"Name",value:"colorName"}}]}}]}}]};

  CopilotTools.mutations.DELETE_TAG = {kind:"Document",definitions:[{kind:"OperationDefinition",operation:"mutation",name:{kind:"Name",value:"DeleteTag"},variableDefinitions:[{kind:"VariableDefinition",variable:{kind:"Variable",name:{kind:"Name",value:"id"}},type:{kind:"NonNullType",type:{kind:"NamedType",name:{kind:"Name",value:"ID"}}}}],selectionSet:{kind:"SelectionSet",selections:[{kind:"Field",name:{kind:"Name",value:"deleteTag"},arguments:[{kind:"Argument",name:{kind:"Name",value:"id"},value:{kind:"Variable",name:{kind:"Name",value:"id"}}}]}]}}]};

  CopilotTools.mutations.DELETE_CATEGORY = {kind:"Document",definitions:[{kind:"OperationDefinition",operation:"mutation",name:{kind:"Name",value:"DeleteCategory"},variableDefinitions:[{kind:"VariableDefinition",variable:{kind:"Variable",name:{kind:"Name",value:"id"}},type:{kind:"NonNullType",type:{kind:"NamedType",name:{kind:"Name",value:"ID"}}}}],selectionSet:{kind:"SelectionSet",selections:[{kind:"Field",name:{kind:"Name",value:"deleteCategory"},arguments:[{kind:"Argument",name:{kind:"Name",value:"id"},value:{kind:"Variable",name:{kind:"Name",value:"id"}}}]}]}}]};

  // LOOKUP FUNCTIONS
  CopilotTools.buildLookups = function() { var cache = window.__APOLLO_CLIENT__.cache.extract(); var accounts = {}; var categories = {}; var tags = {}; var recurrings = {}; for (var key in cache) { if (key.indexOf("Account:") === 0 && cache[key].name) { var acc = cache[key]; var name = acc.name; if (accounts[name]) name = acc.name + " (" + (acc.mask || acc.id.slice(-4)) + ")"; accounts[name] = {id:acc.id,itemId:acc.itemId,name:acc.name,type:acc.type,mask:acc.mask,subtype:acc.subtype,isHidden:acc.isHidden,nickname:acc.nickname}; } if (key.indexOf("Category:") === 0 && cache[key].name) { var cat = cache[key]; categories[cat.name] = {id:cat.id,name:cat.name,colorName:cat.colorName,icon:cat.icon,canBeDeleted:cat.canBeDeleted,isExcluded:cat.isExcluded,childCategories:cat.childCategories,templateId:cat.templateId}; } if (key.indexOf("Tag:") === 0 && cache[key].name) { var tag = cache[key]; tags[tag.name] = {id:tag.id,name:tag.name,colorName:tag.colorName}; } if (key.indexOf("Recurring:") === 0 && cache[key].name) { var rec = cache[key]; recurrings[rec.name] = {id:rec.id,name:rec.name,frequency:rec.frequency,amount:rec.amount}; } } return {accounts:accounts,categories:categories,tags:tags,recurrings:recurrings}; };

  CopilotTools.showAccounts = function() { var lookups = CopilotTools.buildLookups(); return Object.keys(lookups.accounts).sort(); };
  CopilotTools.showCategories = function() { var lookups = CopilotTools.buildLookups(); return Object.keys(lookups.categories).sort(); };
  CopilotTools.showTags = function() { var lookups = CopilotTools.buildLookups(); return Object.keys(lookups.tags); };
  CopilotTools.showRecurrings = function() { var lookups = CopilotTools.buildLookups(); return Object.keys(lookups.recurrings).sort(); };

  // TRANSACTION CACHE FUNCTIONS
  CopilotTools.getCachedTransactions = function() { var cache = window.__APOLLO_CLIENT__.cache.extract(); var transactions = []; for (var key in cache) { if (key.indexOf("Transaction:") === 0) transactions.push(cache[key]); } return transactions; };

  CopilotTools.createTransactionKey = function(tx) { var normalizedName = (tx.name || "").toLowerCase().trim(); var normalizedAmount = parseFloat(tx.amount || 0).toFixed(2); return tx.date + "|" + normalizedName + "|" + normalizedAmount + "|" + tx.accountId; };

  CopilotTools.findDuplicatesInCache = function() { var transactions = CopilotTools.getCachedTransactions(); var seen = {}; var duplicates = []; for (var i = 0; i < transactions.length; i++) { var tx = transactions[i]; var key = CopilotTools.createTransactionKey(tx); if (seen[key]) duplicates.push({original:seen[key],duplicate:tx}); else seen[key] = tx; } return duplicates; };

  CopilotTools.wouldBeDuplicate = function(newTx) { var transactions = CopilotTools.getCachedTransactions(); var newKey = CopilotTools.createTransactionKey(newTx); for (var i = 0; i < transactions.length; i++) { if (CopilotTools.createTransactionKey(transactions[i]) === newKey) return {isDuplicate:true,existingTransaction:transactions[i]}; } return {isDuplicate:false}; };

  CopilotTools.getDateRange = function() { var txs = CopilotTools.getCachedTransactions(); if (txs.length === 0) return {min:null,max:null,count:0}; var dates = []; for (var i = 0; i < txs.length; i++) if (txs[i].date) dates.push(txs[i].date); dates.sort(); return {min:dates[0],max:dates[dates.length-1],count:txs.length}; };

  CopilotTools.searchTransactions = function(query, options) { options = options || {}; var transactions = CopilotTools.getCachedTransactions(); var lookups = CopilotTools.buildLookups(); var results = []; var queryLower = (query || "").toLowerCase(); for (var i = 0; i < transactions.length; i++) { var tx = transactions[i]; if (queryLower && tx.name && tx.name.toLowerCase().indexOf(queryLower) === -1) continue; if (options.startDate && tx.date < options.startDate) continue; if (options.endDate && tx.date > options.endDate) continue; if (options.accountName) { var accountMatch = false; for (var accName in lookups.accounts) { if (lookups.accounts[accName].id === tx.accountId && accName.toLowerCase().indexOf(options.accountName.toLowerCase()) >= 0) { accountMatch = true; break; } } if (!accountMatch) continue; } if (options.categoryName) { var cat = lookups.categories[options.categoryName]; if (!cat || cat.id !== tx.categoryId) continue; } results.push(tx); } results.sort(function(a,b){return (b.date||"").localeCompare(a.date||"");}); return results; };

  CopilotTools.findTransaction = function(query) { var results = CopilotTools.searchTransactions(query); return results.length > 0 ? results[0] : null; };

  CopilotTools.findTransactionsByPattern = function(pattern, options) { options = options || {}; var transactions = CopilotTools.getCachedTransactions(); var results = []; var patternLower = (pattern || "").toLowerCase(); var words = patternLower.split(/s+/); for (var i = 0; i < transactions.length; i++) { var tx = transactions[i]; var nameLower = (tx.name || "").toLowerCase(); var allMatch = true; for (var j = 0; j < words.length; j++) { if (words[j] && nameLower.indexOf(words[j]) === -1) { allMatch = false; break; } } if (allMatch) { if (options.startDate && tx.date < options.startDate) continue; if (options.endDate && tx.date > options.endDate) continue; results.push(tx); } } return results; };

  // CREATE TRANSACTION
  CopilotTools.createTransaction = function(options) { var accountName = options.accountName; var date = options.date; var name = options.name; var amount = options.amount; var categoryName = options.categoryName || ""; var type = (options.type || "REGULAR").toUpperCase(); var notes = options.notes || null; var tagIds = options.tagIds || []; var recurringId = options.recurringId || null; var skipDuplicateCheck = options.skipDuplicateCheck || false; if (type === "INTERNAL TRANSFER") type = "INTERNAL_TRANSFER"; if (type !== "REGULAR" && type !== "INCOME" && type !== "INTERNAL_TRANSFER") type = "REGULAR"; var lookups = CopilotTools.buildLookups(); var account = lookups.accounts[accountName]; if (!account) { var accountKeys = Object.keys(lookups.accounts); for (var i = 0; i < accountKeys.length; i++) { var k = accountKeys[i]; if (k.indexOf(accountName) >= 0 || accountName.indexOf(k.split(" (")[0]) >= 0) { account = lookups.accounts[k]; break; } } } if (!account) return Promise.resolve({success:false,error:"Account not found: " + accountName}); var categoryId = ""; if (categoryName && categoryName !== "") { var category = lookups.categories[categoryName]; if (category) categoryId = category.id; else if (type === "REGULAR") return Promise.resolve({success:false,error:"Category not found: " + categoryName}); } else if (type === "REGULAR") return Promise.resolve({success:false,error:"Category required for REGULAR transactions"}); var resolvedTagIds = []; if (tagIds && tagIds.length > 0) { for (var t = 0; t < tagIds.length; t++) { var tagInput = tagIds[t]; if (typeof tagInput === "string") { var foundTag = lookups.tags[tagInput]; resolvedTagIds.push(foundTag ? foundTag.id : tagInput); } else resolvedTagIds.push(tagInput); } } if (!skipDuplicateCheck) { var dupCheck = CopilotTools.wouldBeDuplicate({date:date,name:name,amount:parseFloat(amount),accountId:account.id}); if (dupCheck.isDuplicate) return Promise.resolve({success:false,error:"DUPLICATE_DETECTED",existingTransaction:dupCheck.existingTransaction}); } return window.__APOLLO_CLIENT__.mutate({mutation:CopilotTools.mutations.CREATE_TRANSACTION,variables:{accountId:account.id,itemId:account.itemId,input:{categoryId:categoryId,amount:Math.abs(parseFloat(amount)),name:name,type:type,date:date,recurringId:recurringId,userNotes:notes,tagIds:resolvedTagIds}}}).then(function(result){CopilotTools.log("Created transaction: " + name + " $" + amount);return {success:true,id:result.data.createTransaction.id,data:result.data.createTransaction};}).catch(function(error){CopilotTools.error("Create failed: " + error.message);return {success:false,error:error.message};}); };

  // DELETE TRANSACTION
  CopilotTools.deleteTransaction = function(txId, accountId, itemId) { if (!accountId || !itemId) { var cache = window.__APOLLO_CLIENT__.cache.extract(); for (var key in cache) { if (key.indexOf("Transaction:") === 0 && cache[key].id === txId) { accountId = cache[key].accountId; itemId = cache[key].itemId; break; } } } if (!accountId || !itemId) return Promise.resolve({success:false,error:"Could not find accountId/itemId for: " + txId}); return window.__APOLLO_CLIENT__.mutate({mutation:CopilotTools.mutations.DELETE_TRANSACTION,variables:{accountId:accountId,itemId:itemId,id:txId}}).then(function(){CopilotTools.log("Deleted transaction: " + txId);return {success:true};}).catch(function(error){CopilotTools.error("Delete failed: " + error.message);return {success:false,error:error.message};}); };

  // BATCH CREATE
  CopilotTools.batchCreateTransactions = function(transactions, options) { options = options || {}; var delayMs = options.delayMs || CopilotTools.config.rateLimit; var stopOnDuplicate = options.stopOnDuplicate !== false; var dryRun = options.dryRun || false; var results = {total:transactions.length,created:[],duplicates:[],errors:[],skipped:[]}; CopilotTools.log("Starting batch: " + transactions.length + " transactions" + (dryRun ? " (DRY RUN)" : "")); var processNext = function(index) { if (index >= transactions.length) { CopilotTools.log("Batch complete: " + results.created.length + " created, " + results.duplicates.length + " duplicates, " + results.errors.length + " errors"); return Promise.resolve(results); } var tx = transactions[index]; var progress = "[" + (index+1) + "/" + transactions.length + "]"; if (!tx.accountName || !tx.date || !tx.name || tx.amount === undefined) { results.errors.push({tx:tx,error:"Missing required fields"}); CopilotTools.warn(progress + " SKIP (missing fields): " + tx.name); return processNext(index+1); } if (parseFloat(tx.amount) === 0) { results.skipped.push({tx:tx,reason:"zero amount"}); CopilotTools.log(progress + " SKIP (zero amount): " + tx.name); return processNext(index+1); } if (dryRun) { var lookups = CopilotTools.buildLookups(); var acc = null; for (var k in lookups.accounts) { if (k.indexOf(tx.accountName) >= 0 || tx.accountName.indexOf(k.split(" (")[0]) >= 0) { acc = lookups.accounts[k]; break; } } var dupCheck = CopilotTools.wouldBeDuplicate({date:tx.date,name:tx.name,amount:parseFloat(tx.amount),accountId:acc?acc.id:null}); if (dupCheck.isDuplicate) { results.duplicates.push({tx:tx,existingId:dupCheck.existingTransaction.id}); CopilotTools.log(progress + " WOULD BE DUPLICATE: " + tx.name); } else { results.created.push(tx); CopilotTools.log(progress + " WOULD CREATE: " + tx.name + " $" + tx.amount + " [" + (tx.type||"REGULAR") + "]"); } return processNext(index+1); } return CopilotTools.createTransaction(tx).then(function(result) { if (result.success) { results.created.push({tx:tx,id:result.id}); CopilotTools.log(progress + " CREATED: " + tx.name + " $" + tx.amount); } else if (result.error === "DUPLICATE_DETECTED") { results.duplicates.push({tx:tx,existing:result.existingTransaction}); CopilotTools.warn(progress + " DUPLICATE: " + tx.name); if (stopOnDuplicate) { CopilotTools.error("Stopping. Set stopOnDuplicate=false to continue."); return results; } } else { results.errors.push({tx:tx,error:result.error}); CopilotTools.error(progress + " ERROR: " + result.error); } if (index < transactions.length - 1) return CopilotTools._delay(delayMs).then(function(){return processNext(index+1);}); return processNext(index+1); }); }; return processNext(0); };

  // TAG MANAGEMENT
  CopilotTools.createTag = function(options) { var name = options.name; var colorName = options.colorName || "BLUE1"; if (!name) return Promise.resolve({success:false,error:"Tag name is required"}); var lookups = CopilotTools.buildLookups(); if (lookups.tags[name]) return Promise.resolve({success:false,error:"Tag already exists: " + name,existing:lookups.tags[name]}); return window.__APOLLO_CLIENT__.mutate({mutation:CopilotTools.mutations.CREATE_TAG,variables:{input:{name:name,colorName:colorName}}}).then(function(result){CopilotTools.log("Created tag: " + name);return {success:true,id:result.data.createTag.id,data:result.data.createTag};}).catch(function(error){CopilotTools.error("Create tag failed: " + error.message);return {success:false,error:error.message};}); };

  CopilotTools.deleteTag = function(tagIdOrName) { var lookups = CopilotTools.buildLookups(); var tagId = tagIdOrName; if (lookups.tags[tagIdOrName]) tagId = lookups.tags[tagIdOrName].id; return window.__APOLLO_CLIENT__.mutate({mutation:CopilotTools.mutations.DELETE_TAG,variables:{id:tagId}}).then(function(){CopilotTools.log("Deleted tag: " + tagIdOrName);return {success:true};}).catch(function(error){CopilotTools.error("Delete tag failed: " + error.message);return {success:false,error:error.message};}); };

  // CATEGORY MANAGEMENT
  CopilotTools.deleteCategory = function(categoryIdOrName) { var lookups = CopilotTools.buildLookups(); var categoryId = categoryIdOrName; var categoryName = categoryIdOrName; if (lookups.categories[categoryIdOrName]) categoryId = lookups.categories[categoryIdOrName].id; else { for (var name in lookups.categories) { if (lookups.categories[name].id === categoryIdOrName) { categoryName = name; break; } } } var cat = lookups.categories[categoryName]; if (cat && cat.canBeDeleted === false) return Promise.resolve({success:false,error:"Category cannot be deleted: " + categoryName}); return window.__APOLLO_CLIENT__.mutate({mutation:CopilotTools.mutations.DELETE_CATEGORY,variables:{id:categoryId}}).then(function(){CopilotTools.log("Deleted category: " + categoryName);return {success:true};}).catch(function(error){CopilotTools.error("Delete category failed: " + error.message);return {success:false,error:error.message};}); };

  CopilotTools.findByCategory = function(categoryName) { var lookups = CopilotTools.buildLookups(); var cat = lookups.categories[categoryName]; if (!cat) { CopilotTools.warn("Category not found: " + categoryName); return []; } var transactions = CopilotTools.getCachedTransactions(); var results = []; for (var i = 0; i < transactions.length; i++) { if (transactions[i].categoryId === cat.id) results.push(transactions[i]); } return results.sort(function(a,b){return (b.date||"").localeCompare(a.date||"");}); };

  CopilotTools.findUncategorized = function() { var lookups = CopilotTools.buildLookups(); var otherCategory = lookups.categories["Other"]; var otherCategoryId = otherCategory ? otherCategory.id : null; var transactions = CopilotTools.getCachedTransactions(); var results = []; for (var i = 0; i < transactions.length; i++) { var tx = transactions[i]; if (tx.type === "REGULAR" || !tx.type) { if (!tx.categoryId || tx.categoryId === otherCategoryId) results.push(tx); } } return results.sort(function(a,b){return (b.date||"").localeCompare(a.date||"");}); };

  CopilotTools.getCategoryBreakdown = function() { var lookups = CopilotTools.buildLookups(); var transactions = CopilotTools.getCachedTransactions(); var breakdown = {}; for (var catName in lookups.categories) breakdown[catName] = {count:0,total:0,transactions:[]}; breakdown["Uncategorized"] = {count:0,total:0,transactions:[]}; for (var i = 0; i < transactions.length; i++) { var tx = transactions[i]; var categoryName = "Uncategorized"; for (var cn in lookups.categories) { if (lookups.categories[cn].id === tx.categoryId) { categoryName = cn; break; } } if (!breakdown[categoryName]) breakdown[categoryName] = {count:0,total:0,transactions:[]}; breakdown[categoryName].count++; breakdown[categoryName].total += parseFloat(tx.amount||0); breakdown[categoryName].transactions.push(tx.id); } var result = []; for (var name in breakdown) { if (breakdown[name].count > 0) result.push({name:name,count:breakdown[name].count,total:Math.round(breakdown[name].total*100)/100}); } return result.sort(function(a,b){return b.count - a.count;}); };

  // AUTO-CATEGORIZATION
  CopilotTools._defaultRules = [{pattern:"costco",category:"Groceries",priority:10},{pattern:"trader joe",category:"Groceries",priority:10},{pattern:"whole foods",category:"Groceries",priority:10},{pattern:"safeway",category:"Groceries",priority:10},{pattern:"kroger",category:"Groceries",priority:10},{pattern:"walmart",category:"Shops",priority:5},{pattern:"target",category:"Shops",priority:5},{pattern:"amazon",category:"Shops",priority:3},{pattern:"netflix",category:"Subscriptions",priority:10},{pattern:"spotify",category:"Subscriptions",priority:10},{pattern:"hulu",category:"Subscriptions",priority:10},{pattern:"uber eats",category:"Restaurants",priority:10},{pattern:"doordash",category:"Restaurants",priority:10},{pattern:"grubhub",category:"Restaurants",priority:10},{pattern:"uber trip",category:"Transportation",priority:10},{pattern:"lyft",category:"Transportation",priority:10},{pattern:"shell",category:"Car",priority:10},{pattern:"chevron",category:"Car",priority:10},{pattern:"pharmacy",category:"Healthcare",priority:5},{pattern:"cvs",category:"Healthcare",priority:5},{pattern:"doctor",category:"Healthcare",priority:8}];

  CopilotTools.addAutoCategorizeRule = function(pattern, category, options) { options = options || {}; var rule = {id:"rule_" + Date.now() + "_" + Math.random().toString(36).substr(2,9),pattern:pattern.toLowerCase(),category:category,priority:options.priority || 5,tags:options.tags || [],createdAt:new Date().toISOString()}; CopilotTools._categorizationRules.push(rule); CopilotTools._categorizationRules.sort(function(a,b){return b.priority - a.priority;}); CopilotTools.log("Added rule: " + pattern + " -> " + category); return rule; };

  CopilotTools.listRules = function(includeDefaults) { var rules = CopilotTools._categorizationRules.slice(); if (includeDefaults !== false) rules = rules.concat(CopilotTools._defaultRules); return rules.sort(function(a,b){return b.priority - a.priority;}); };

  CopilotTools.deleteRule = function(ruleId) { var index = -1; for (var i = 0; i < CopilotTools._categorizationRules.length; i++) { if (CopilotTools._categorizationRules[i].id === ruleId) { index = i; break; } } if (index >= 0) { CopilotTools._categorizationRules.splice(index, 1); CopilotTools.log("Deleted rule: " + ruleId); return true; } return false; };

  CopilotTools.suggestCategory = function(transactionName) { var nameLower = (transactionName || "").toLowerCase(); var rules = CopilotTools.listRules(true); for (var i = 0; i < rules.length; i++) { var rule = rules[i]; if (nameLower.indexOf(rule.pattern) >= 0) return {category:rule.category,matchedRule:rule,confidence:rule.priority/10}; } var transactions = CopilotTools.getCachedTransactions(); var lookups = CopilotTools.buildLookups(); var words = nameLower.split(/s+/); var categoryVotes = {}; for (var j = 0; j < transactions.length; j++) { var tx = transactions[j]; if (tx.categoryId && tx.name) { var txNameLower = tx.name.toLowerCase(); var matches = 0; for (var w = 0; w < words.length; w++) { if (words[w].length > 2 && txNameLower.indexOf(words[w]) >= 0) matches++; } if (matches > 0) { if (!categoryVotes[tx.categoryId]) categoryVotes[tx.categoryId] = 0; categoryVotes[tx.categoryId] += matches; } } } var bestCategoryId = null; var bestScore = 0; for (var catId in categoryVotes) { if (categoryVotes[catId] > bestScore) { bestScore = categoryVotes[catId]; bestCategoryId = catId; } } if (bestCategoryId) { for (var catName in lookups.categories) { if (lookups.categories[catName].id === bestCategoryId) return {category:catName,matchedRule:null,confidence:Math.min(bestScore/10,0.8),basedOnSimilar:true}; } } return null; };

  CopilotTools.reviewUncategorized = function() { var uncategorized = CopilotTools.findUncategorized(); var results = []; for (var i = 0; i < uncategorized.length; i++) { var tx = uncategorized[i]; var suggestion = CopilotTools.suggestCategory(tx.name); results.push({id:tx.id,name:tx.name,amount:tx.amount,date:tx.date,suggestion:suggestion}); } return results; };

  // AMAZON MATCHING
  CopilotTools.findAmazonTransactions = function() { var transactions = CopilotTools.getCachedTransactions(); var results = []; for (var i = 0; i < transactions.length; i++) { var tx = transactions[i]; var nameLower = (tx.name || "").toLowerCase(); if (nameLower.indexOf("amazon") >= 0 || nameLower.indexOf("amzn") >= 0 || nameLower.indexOf("prime video") >= 0) results.push(tx); } return results.sort(function(a,b){return (b.date||"").localeCompare(a.date||"");}); };

  CopilotTools.matchAmazonOrders = function(amazonOrders) { var amazonTxs = CopilotTools.findAmazonTransactions(); var results = []; for (var i = 0; i < amazonOrders.length; i++) { var order = amazonOrders[i]; var orderAmount = Math.abs(parseFloat(order.amount)); var matches = []; for (var j = 0; j < amazonTxs.length; j++) { var tx = amazonTxs[j]; var txAmount = Math.abs(parseFloat(tx.amount)); var amountMatch = Math.abs(txAmount - orderAmount) < 0.02; var orderDateObj = new Date(order.date); var txDateObj = new Date(tx.date); var daysDiff = Math.abs((orderDateObj - txDateObj) / (1000*60*60*24)); var dateMatch = daysDiff <= 5; if (amountMatch && dateMatch) matches.push({transaction:tx,daysDiff:daysDiff,exactMatch:daysDiff<=1&&Math.abs(txAmount-orderAmount)<0.01}); } matches.sort(function(a,b){if(a.exactMatch!==b.exactMatch)return b.exactMatch?1:-1;return a.daysDiff-b.daysDiff;}); results.push({order:order,matches:matches,bestMatch:matches.length>0?matches[0]:null}); } return results; };

  // CSV IMPORT/EXPORT
  CopilotTools.parseCSV = function(csv) { var lines = csv.split("\n"); var headers = []; var rows = []; for (var i = 0; i < lines.length; i++) { var line = lines[i].trim(); if (!line) continue; var cells = line.split(","); if (i === 0) { headers = cells; continue; } var row = {}; for (var j = 0; j < headers.length; j++) row[headers[j].toLowerCase().trim()] = (cells[j] || "").trim(); rows.push(row); } return rows; };

  CopilotTools.importFromCSV = function(csvString, options) { options = options || {}; var dryRun = options.dryRun || false; var categoryMapping = options.categoryMapping || {}; var accountMapping = options.accountMapping || {}; var rows = CopilotTools.parseCSV(csvString); var transactions = []; for (var i = 0; i < rows.length; i++) { var row = rows[i]; var date = row.date || row["transaction date"] || ""; var name = row.name || row.description || row.merchant || ""; var amount = row.amount || "0"; var category = row.category || ""; var account = row.account || row["account name"] || ""; var type = row.type || "REGULAR"; var notes = row.notes || row.memo || ""; if (categoryMapping[category]) category = categoryMapping[category]; if (accountMapping[account]) account = accountMapping[account]; if (date && name && amount) transactions.push({date:date,name:name,amount:parseFloat(amount.replace(/[^0-9.-]/g,"")),categoryName:category,accountName:account,type:type.toUpperCase(),notes:notes||null}); } CopilotTools.log("Parsed " + transactions.length + " transactions from CSV"); return CopilotTools.batchCreateTransactions(transactions, {dryRun:dryRun,stopOnDuplicate:false}); };

  CopilotTools.exportToJSON = function() { var lookups = CopilotTools.buildLookups(); var transactions = CopilotTools.getCachedTransactions(); return {version:CopilotTools.VERSION,exportedAt:new Date().toISOString(),accounts:lookups.accounts,categories:lookups.categories,tags:lookups.tags,recurrings:lookups.recurrings,transactions:transactions,rules:CopilotTools._categorizationRules}; };

  CopilotTools.downloadFile = function(content, filename, mimeType) { mimeType = mimeType || "application/json"; var blob = new Blob([content], {type:mimeType}); var url = URL.createObjectURL(blob); var a = document.createElement("a"); a.href = url; a.download = filename; document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(url); CopilotTools.log("Downloaded: " + filename); };

  CopilotTools.downloadBackup = function(filename) { var backup = CopilotTools.exportToJSON(); filename = filename || ("copilot-backup-" + new Date().toISOString().split("T")[0] + ".json"); CopilotTools.downloadFile(JSON.stringify(backup, null, 2), filename); };

  // DUPLICATE ANALYSIS
  CopilotTools.analyzeForDuplicates = function(txArray, options) { options = options || {}; var lookups = CopilotTools.buildLookups(); var analysis = {total:txArray.length,wouldCreate:[],wouldBeDuplicates:[],missingAccounts:[],missingCategories:[],zeroAmount:[]}; for (var i = 0; i < txArray.length; i++) { var tx = txArray[i]; if (parseFloat(tx.amount) === 0) { analysis.zeroAmount.push(tx); continue; } var acc = null; for (var k in lookups.accounts) { if (k.indexOf(tx.accountName) >= 0 || tx.accountName.indexOf(k.split(" (")[0]) >= 0) { acc = lookups.accounts[k]; break; } } if (!acc) { analysis.missingAccounts.push({tx:tx,accountName:tx.accountName}); continue; } var type = (tx.type || "REGULAR").toUpperCase(); if (type === "REGULAR" && tx.categoryName && !lookups.categories[tx.categoryName]) { analysis.missingCategories.push({tx:tx,categoryName:tx.categoryName}); continue; } var dupCheck = CopilotTools.wouldBeDuplicate({date:tx.date,name:tx.name,amount:parseFloat(tx.amount),accountId:acc.id}); if (dupCheck.isDuplicate) analysis.wouldBeDuplicates.push({newTx:tx,existingTx:dupCheck.existingTransaction}); else analysis.wouldCreate.push(tx); } return analysis; };

  CopilotTools.printDuplicateAnalysis = function(analysis) { console.log("=== DUPLICATE ANALYSIS ==="); console.log("Total transactions: " + analysis.total); console.log("Would create: " + analysis.wouldCreate.length); console.log("Would be duplicates: " + analysis.wouldBeDuplicates.length); console.log("Missing accounts: " + analysis.missingAccounts.length); console.log("Missing categories: " + analysis.missingCategories.length); console.log("Zero amount (skipped): " + analysis.zeroAmount.length); if (analysis.wouldBeDuplicates.length > 0) { console.log("--- DUPLICATES ---"); for (var i = 0; i < Math.min(analysis.wouldBeDuplicates.length, 10); i++) { var dup = analysis.wouldBeDuplicates[i]; console.log("  " + dup.newTx.date + " | " + dup.newTx.name + " | $" + dup.newTx.amount); } if (analysis.wouldBeDuplicates.length > 10) console.log("  ... and " + (analysis.wouldBeDuplicates.length - 10) + " more"); } if (analysis.missingAccounts.length > 0) { console.log("--- MISSING ACCOUNTS ---"); var uniqueAccounts = {}; for (var j = 0; j < analysis.missingAccounts.length; j++) uniqueAccounts[analysis.missingAccounts[j].accountName] = true; console.log("  " + Object.keys(uniqueAccounts).join(", ")); } return analysis; };

  // STATUS AND UTILITY
  CopilotTools.status = function() { var lookups = CopilotTools.buildLookups(); var range = CopilotTools.getDateRange(); var dups = CopilotTools.findDuplicatesInCache(); console.log("=== COPILOT TOOLS v" + CopilotTools.VERSION + " STATUS ==="); console.log("Accounts: " + Object.keys(lookups.accounts).length); console.log("Categories: " + Object.keys(lookups.categories).length); console.log("Tags: " + Object.keys(lookups.tags).length); console.log("Recurrings: " + Object.keys(lookups.recurrings).length); console.log("Transactions in cache: " + range.count); console.log("Date range: " + range.min + " to " + range.max); console.log("Duplicates: " + dups.length); return {accounts:Object.keys(lookups.accounts).length,categories:Object.keys(lookups.categories).length,tags:Object.keys(lookups.tags).length,recurrings:Object.keys(lookups.recurrings).length,transactions:range.count,dateRange:range,duplicates:dups.length}; };

  CopilotTools.findTestTransactions = function() { var txs = CopilotTools.getCachedTransactions(); return txs.filter(function(tx) { return tx.name && tx.name.toUpperCase().indexOf("TEST") >= 0; }); };

  CopilotTools.deleteTestTransactions = function() { var testTxs = CopilotTools.findTestTransactions(); var results = {deleted:[],errors:[]}; if (testTxs.length === 0) { CopilotTools.log("No test transactions found"); return Promise.resolve(results); } CopilotTools.log("Found " + testTxs.length + " test transactions to delete"); var deleteNext = function(index) { if (index >= testTxs.length) { CopilotTools.log("Deleted " + results.deleted.length + " test transactions"); return Promise.resolve(results); } return CopilotTools.deleteTransaction(testTxs[index].id).then(function(result) { if (result.success) results.deleted.push(testTxs[index].id); else results.errors.push({id:testTxs[index].id,error:result.error}); return CopilotTools._delay(CopilotTools.config.rateLimit); }).then(function(){return deleteNext(index+1);}); }; return deleteNext(0); };

  // HELP
  CopilotTools.help = function() { console.log(""); console.log("=== COPILOT TOOLS v" + CopilotTools.VERSION + " HELP ==="); console.log(""); console.log("STATUS & INFO:"); console.log("  CopilotTools.status()           - Show current state"); console.log("  CopilotTools.showAccounts()     - List accounts"); console.log("  CopilotTools.showCategories()   - List categories"); console.log("  CopilotTools.showTags()         - List tags"); console.log("  CopilotTools.showRecurrings()   - List recurring transactions"); console.log(""); console.log("TRANSACTIONS:"); console.log("  CopilotTools.createTransaction({accountName, date, name, amount, categoryName, type, notes})"); console.log("  CopilotTools.deleteTransaction(txId)"); console.log("  CopilotTools.batchCreateTransactions(txArray, {dryRun: true})"); console.log("  CopilotTools.searchTransactions(query, {startDate, endDate})"); console.log("  CopilotTools.findTransaction(query)"); console.log(""); console.log("DUPLICATE DETECTION:"); console.log("  CopilotTools.analyzeForDuplicates(txArray, {datePrefix})"); console.log("  CopilotTools.printDuplicateAnalysis(analysis)"); console.log("  CopilotTools.wouldBeDuplicate({date, name, amount, accountId})"); console.log(""); console.log("TAGS:"); console.log("  CopilotTools.createTag({name, colorName})"); console.log("  CopilotTools.deleteTag(tagId or tagName)"); console.log(""); console.log("CATEGORIES:"); console.log("  CopilotTools.deleteCategory(categoryId or categoryName)"); console.log("  CopilotTools.findByCategory(categoryName)"); console.log("  CopilotTools.findUncategorized()"); console.log(""); console.log("AUTO-CATEGORIZATION:"); console.log("  CopilotTools.suggestCategory(transactionName)"); console.log("  CopilotTools.reviewUncategorized()"); console.log("  CopilotTools.addAutoCategorizeRule(pattern, category)"); console.log(""); console.log("AMAZON MATCHING:"); console.log("  CopilotTools.findAmazonTransactions()"); console.log("  CopilotTools.matchAmazonOrders(amazonOrders)"); console.log(""); console.log("CONSTANTS:"); console.log("  CopilotTools.COLORS - Available colors for tags/categories"); console.log("  CopilotTools.TRANSACTION_TYPES - REGULAR, INCOME, INTERNAL_TRANSFER"); };

  // INITIALIZATION
  console.log("=== COPILOT TOOLS v" + CopilotTools.VERSION + " LOADED ===");
  console.log("Run CopilotTools.status() to verify setup.");
  console.log("Run CopilotTools.help() for full command list.");

})();